package Views;

import Controllers.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;

public class JF_Cliente extends javax.swing.JFrame {

    
    public JF_Cliente() 
    {
        initComponents();
        LimpiarTabla();
        LlenarTabla();
    }
    
    //metodo que limpia la tabla
    public void LimpiarTabla()
    {
        
        for(int i = 0; i < Tbl_Cliente.getRowCount(); i++)
        {
            DefaultTableModel m = (DefaultTableModel) Tbl_Cliente.getModel();
            m.removeRow(i);
            i -= 1;
        }  
    }
    
    //llenamos la tabla
    public void LlenarTabla()
    {
        
        Object[][] TemCli = null;
        //llamo al metodo de la clase que realiza el llenado 
        C_Cliente cliente = new C_Cliente();
        TemCli = cliente.cargarTabla();
        
        DefaultTableModel modelo3 = (DefaultTableModel) Tbl_Cliente.getModel();
        
        for(int i = 0; i < TemCli.length; i++)
        {
            modelo3.addRow(TemCli[i]);
        }
        Tbl_Cliente.setModel(modelo3);   
    }
    
    //mostrar data 
    public void MostrarTabla()
    { 
        int id_cliente = 0;
        
        DefaultTableModel m2 = (DefaultTableModel) Tbl_Cliente.getModel();
        String id = String.valueOf(m2.getValueAt(Tbl_Cliente.getSelectedRow(), 1));
        String nombre = String.valueOf(m2.getValueAt(Tbl_Cliente.getSelectedRow(), 2));
        String apellido = String.valueOf(m2.getValueAt(Tbl_Cliente.getSelectedRow(), 3));
        String direccion = String.valueOf(m2.getValueAt(Tbl_Cliente.getSelectedRow(), 4));
        String nacimiento = String.valueOf(m2.getValueAt(Tbl_Cliente.getSelectedRow(), 5));
        String telefono = String.valueOf(m2.getValueAt(Tbl_Cliente.getSelectedRow(), 6));
        String correo = String.valueOf(m2.getValueAt(Tbl_Cliente.getSelectedRow(), 7));
  
        id_cliente = Integer.parseInt(id);
        String idC = Integer.toString(id_cliente);
        
        Txt_IdCliente.setText(idC);
        Txt_Nombre.setText(nombre);
        Txt_Apellidos.setText(apellido); 
        Txt_Direccion.setText(direccion); 
        Txt_Fecha.setText(nacimiento);
        Txt_Telefono.setText(telefono);
        Txt_Correo.setText(correo); 
    }
    
    public void LimpiarCampos()
    {
        Txt_IdCliente.setText("");
        Txt_Nombre.setText("");
        Txt_Apellidos.setText(""); 
        Txt_Direccion.setText(""); 
        Txt_Fecha.setText("");
        Txt_Telefono.setText("");
        Txt_Correo.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Lbl_Nombre = new javax.swing.JLabel();
        Lbl_Apellidos = new javax.swing.JLabel();
        Lbl_Direccion = new javax.swing.JLabel();
        Lbl_Nacimiento = new javax.swing.JLabel();
        Lbl_Telefono = new javax.swing.JLabel();
        Lbl_Email = new javax.swing.JLabel();
        Txt_Nombre = new javax.swing.JTextField();
        Txt_Apellidos = new javax.swing.JTextField();
        Txt_Telefono = new javax.swing.JTextField();
        Txt_Fecha = new javax.swing.JTextField();
        Txt_Direccion = new javax.swing.JTextField();
        Txt_Correo = new javax.swing.JTextField();
        Lbl_Cliente = new javax.swing.JLabel();
        Txt_IdCliente = new javax.swing.JTextField();
        Btn_Guardar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Btn_VolverMenu = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tbl_Cliente = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Lbl_Nombre.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Lbl_Nombre.setForeground(new java.awt.Color(0, 0, 0));
        Lbl_Nombre.setText("Nombre:");

        Lbl_Apellidos.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Lbl_Apellidos.setForeground(new java.awt.Color(0, 0, 0));
        Lbl_Apellidos.setText("Apellidos:");

        Lbl_Direccion.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Lbl_Direccion.setForeground(new java.awt.Color(0, 0, 0));
        Lbl_Direccion.setText("Dirección:");

        Lbl_Nacimiento.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Lbl_Nacimiento.setForeground(new java.awt.Color(0, 0, 0));
        Lbl_Nacimiento.setText("Fecha de Nacimiento:");

        Lbl_Telefono.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Lbl_Telefono.setForeground(new java.awt.Color(0, 0, 0));
        Lbl_Telefono.setText("Teléfono:");

        Lbl_Email.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Lbl_Email.setForeground(new java.awt.Color(0, 0, 0));
        Lbl_Email.setText("Correo electrónico:");

        Txt_Nombre.setBackground(new java.awt.Color(255, 255, 255));
        Txt_Nombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Txt_Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_NombreActionPerformed(evt);
            }
        });

        Txt_Apellidos.setBackground(new java.awt.Color(255, 255, 255));
        Txt_Apellidos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Txt_Apellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_ApellidosActionPerformed(evt);
            }
        });

        Txt_Telefono.setBackground(new java.awt.Color(255, 255, 255));
        Txt_Telefono.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Txt_Telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_TelefonoActionPerformed(evt);
            }
        });

        Txt_Fecha.setBackground(new java.awt.Color(255, 255, 255));
        Txt_Fecha.setForeground(new java.awt.Color(0, 0, 0));
        Txt_Fecha.setText("DD/MM/AAAA");
        Txt_Fecha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Txt_Fecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_FechaActionPerformed(evt);
            }
        });

        Txt_Direccion.setBackground(new java.awt.Color(255, 255, 255));
        Txt_Direccion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Txt_Correo.setBackground(new java.awt.Color(255, 255, 255));
        Txt_Correo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Lbl_Cliente.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Lbl_Cliente.setForeground(new java.awt.Color(0, 0, 0));
        Lbl_Cliente.setText("ID Cliente:");

        Txt_IdCliente.setBackground(new java.awt.Color(102, 102, 102));
        Txt_IdCliente.setEnabled(false);

        Btn_Guardar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Btn_Guardar.setForeground(new java.awt.Color(0, 0, 0));
        Btn_Guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/icono_agregar.png"))); // NOI18N
        Btn_Guardar.setText("Agregar");
        Btn_Guardar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Btn_Guardar.setBorderPainted(false);
        Btn_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_GuardarActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/icono_modificar.png"))); // NOI18N
        jButton1.setText("Modificar");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setBorderPainted(false);

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/icono_eliminar.png"))); // NOI18N
        jButton2.setText("Eliminar");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Datos del Cliente");

        Btn_VolverMenu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Btn_VolverMenu.setText("Volver al menú");
        Btn_VolverMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_VolverMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(Btn_VolverMenu)
                .addGap(111, 111, 111)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Btn_VolverMenu)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        Tbl_Cliente.setBackground(new java.awt.Color(204, 204, 204));
        Tbl_Cliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Apellidos", "Dirección", "Fecha de nacimiento", "Telefono", "Correo electrónico"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Tbl_Cliente);
        if (Tbl_Cliente.getColumnModel().getColumnCount() > 0) {
            Tbl_Cliente.getColumnModel().getColumn(0).setResizable(false);
            Tbl_Cliente.getColumnModel().getColumn(1).setResizable(false);
            Tbl_Cliente.getColumnModel().getColumn(2).setResizable(false);
            Tbl_Cliente.getColumnModel().getColumn(3).setResizable(false);
            Tbl_Cliente.getColumnModel().getColumn(4).setResizable(false);
            Tbl_Cliente.getColumnModel().getColumn(5).setResizable(false);
            Tbl_Cliente.getColumnModel().getColumn(6).setResizable(false);
        }
        Tbl_Cliente.getAccessibleContext().setAccessibleName("Clientes Registrados");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 786, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lbl_Nombre)
                            .addComponent(Lbl_Cliente)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Lbl_Telefono)
                                .addComponent(Lbl_Direccion)))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Txt_Direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Lbl_Nacimiento)
                                .addGap(18, 18, 18)
                                .addComponent(Txt_Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Txt_Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Lbl_Email)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Txt_Correo, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Txt_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Lbl_Apellidos)
                                .addGap(18, 18, 18)
                                .addComponent(Txt_Apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(Btn_Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Txt_IdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(549, 549, 549)))
                                .addGap(18, 18, 18)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Btn_Guardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Lbl_Cliente)
                        .addComponent(Txt_IdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Txt_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lbl_Nombre)
                    .addComponent(Lbl_Apellidos)
                    .addComponent(Txt_Apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl_Direccion)
                    .addComponent(Txt_Direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lbl_Nacimiento)
                    .addComponent(Txt_Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl_Telefono)
                    .addComponent(Txt_Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lbl_Email)
                    .addComponent(Txt_Correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Txt_NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_NombreActionPerformed

    private void Txt_ApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_ApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_ApellidosActionPerformed

    private void Txt_TelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_TelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_TelefonoActionPerformed

    private void Txt_FechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_FechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_FechaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        boolean elimina = false;
        int id_cliente =  Integer.parseInt(Txt_IdCliente.getText());
        
         C_Cliente Cli = new C_Cliente();
         
        try
        { 
            elimina = Cli.Eliminar(id_cliente);
            if(elimina == true)
            {
                JOptionPane.showMessageDialog(null, "Se eliminó la información ", "Información", JOptionPane.INFORMATION_MESSAGE);
            }
            else
            {
                 JOptionPane.showMessageDialog(null, "No se eliminó la información ", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }catch(SQLException ex)
        {
            
        }
         LimpiarTabla();
         LlenarTabla();
         LimpiarCampos();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void Btn_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_GuardarActionPerformed
        // TODO add your handling code here:
        int id;
        String nom,ape,direc,fecha,telefono,correo;
        
        nom = Txt_Nombre.getText().toString();
        ape = Txt_Apellidos.getText().toString();
        direc = Txt_Direccion.getText().toString();
        fecha = Txt_Fecha.getText().toString();
        telefono = Txt_Telefono.getText().toString();
        correo = Txt_Correo.getText().toString();
        
        C_Cliente clientes = new C_Cliente();
        
        try
        {
            if(Txt_Nombre.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Falta ingresar el nombre del cliente ", "Error", JOptionPane.ERROR_MESSAGE);
            }
            else if(Txt_Apellidos.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Falta ingresar los apellidos del cliente ", "Error", JOptionPane.ERROR_MESSAGE);
            }
            else if(Txt_Direccion.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Falta ingresar la direccion del cliente ", "Error", JOptionPane.ERROR_MESSAGE);
            }
            else if(Txt_Fecha.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Falta ingresar la fecha de nacimiento del cliente", "Error", JOptionPane.ERROR_MESSAGE);
            }
            else if(Txt_Telefono.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Falta ingresar el telefono del cliente", "Error", JOptionPane.ERROR_MESSAGE);
            }
            else if(Txt_Correo.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Falta ingresar el correo electronico del cliente ", "Error", JOptionPane.ERROR_MESSAGE);
            }
            else
            {
                id = clientes.Guardar(nom, ape, direc, fecha, telefono, correo);
            }
        }
        catch(SQLException ex)
        {
            Logger.getLogger(JF_Cliente.class.getName()).log(Level.SEVERE, null, ex);
        }
                
        LimpiarTabla();
        LlenarTabla();
        LimpiarCampos();       
        
    }//GEN-LAST:event_Btn_GuardarActionPerformed

    private void Btn_VolverMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_VolverMenuActionPerformed
        // TODO add your handling code here:
        JF_Menu obj = new JF_Menu();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_Btn_VolverMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_Cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Guardar;
    private javax.swing.JButton Btn_VolverMenu;
    private javax.swing.JLabel Lbl_Apellidos;
    private javax.swing.JLabel Lbl_Cliente;
    private javax.swing.JLabel Lbl_Direccion;
    private javax.swing.JLabel Lbl_Email;
    private javax.swing.JLabel Lbl_Nacimiento;
    private javax.swing.JLabel Lbl_Nombre;
    private javax.swing.JLabel Lbl_Telefono;
    private javax.swing.JTable Tbl_Cliente;
    private javax.swing.JTextField Txt_Apellidos;
    private javax.swing.JTextField Txt_Correo;
    private javax.swing.JTextField Txt_Direccion;
    private javax.swing.JTextField Txt_Fecha;
    private javax.swing.JTextField Txt_IdCliente;
    private javax.swing.JTextField Txt_Nombre;
    private javax.swing.JTextField Txt_Telefono;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
