/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Controllers.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;

public class JF_Detalle extends javax.swing.JFrame {

    /**
     * Creates new form JF_Detalle
     */
    public JF_Detalle() 
    {
        initComponents();
        LimpiarTabla();
        LlenarTabla();
    }
    
    //metodo que limpia la tabla
    public void LimpiarTabla()
    {
        
        for(int i = 0; i < Tbl_Detalle.getRowCount(); i++)
        {
            DefaultTableModel m = (DefaultTableModel) Tbl_Detalle.getModel();
            m.removeRow(i);
            i -= 1;
        }  
    }
    
    //llenamos la tabla
    public void LlenarTabla()
    {
        
        Object[][] TemDet = null;
        //llamo al metodo de la clase que realiza el llenado 
        C_Detallle det = new C_Detallle();
        TemDet = det.cargarTabla();
        
        DefaultTableModel modelo3 = (DefaultTableModel) Tbl_Detalle.getModel();
        
        for(int i = 0; i < TemDet.length; i++)
        {
            modelo3.addRow(TemDet[i]);
        }
        Tbl_Detalle.setModel(modelo3);   
    }
    
    //mostrar data 
    public void MostrarTabla()
    { 
        int num_detalle = 0, can = 0;
        
        DefaultTableModel m2 = (DefaultTableModel) Tbl_Detalle.getModel();
        String id = String.valueOf(m2.getValueAt(Tbl_Detalle.getSelectedRow(), 1));
        String factura = String.valueOf(m2.getValueAt(Tbl_Detalle.getSelectedRow(), 2));
        String cantidad = String.valueOf(m2.getValueAt(Tbl_Detalle.getSelectedRow(), 3));
        String precio = String.valueOf(m2.getValueAt(Tbl_Detalle.getSelectedRow(), 4));
       
        can = Integer.parseInt(cantidad);
        
        num_detalle = Integer.parseInt(id);
        String idC = Integer.toString(num_detalle);
        
        Txt_numdetalle.setText(idC);
        Txt_numfactura.setText(factura);
        Txt_precio.setText(precio); 
        
        if(Cmb_Cantidad.getSelectedIndex() == 0)
        {
            can = 1;
        }
        else if(Cmb_Cantidad.getSelectedIndex() == 1)
        {
            can = 1;
        }
    }
    
    public void LimpiarCampos()
    {
        Txt_numdetalle.setText("");
        Txt_numfactura.setText("");
        Txt_precio.setText(""); 
        Cmb_Cantidad.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Lbl_numdetalle = new javax.swing.JLabel();
        Lbl_numfactura1 = new javax.swing.JLabel();
        Lbl_Cantidad = new javax.swing.JLabel();
        Cmb_Cantidad = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tbl_Detalle = new javax.swing.JTable();
        Txt_numdetalle = new javax.swing.JTextField();
        Txt_numfactura = new javax.swing.JTextField();
        Btn_agregar = new javax.swing.JButton();
        Btn_modificar = new javax.swing.JButton();
        Btn_eliminar = new javax.swing.JButton();
        Lbl_precio = new javax.swing.JLabel();
        Txt_precio = new javax.swing.JTextField();
        Btn_volver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel1.setText("Detalle");

        Lbl_numdetalle.setText("Número detalle:");

        Lbl_numfactura1.setText("Número de factura:");

        Lbl_Cantidad.setText("Cantidad:");

        Cmb_Cantidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        Tbl_Detalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Detalle", "ID Factura", "Cantidad", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Tbl_Detalle);
        if (Tbl_Detalle.getColumnModel().getColumnCount() > 0) {
            Tbl_Detalle.getColumnModel().getColumn(0).setResizable(false);
            Tbl_Detalle.getColumnModel().getColumn(1).setResizable(false);
            Tbl_Detalle.getColumnModel().getColumn(2).setResizable(false);
            Tbl_Detalle.getColumnModel().getColumn(3).setResizable(false);
        }

        Txt_numdetalle.setEnabled(false);
        Txt_numdetalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_numdetalleActionPerformed(evt);
            }
        });

        Txt_numfactura.setEnabled(false);

        Btn_agregar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Btn_agregar.setForeground(new java.awt.Color(0, 0, 0));
        Btn_agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/icono_agregar.png"))); // NOI18N
        Btn_agregar.setText("Agregar");
        Btn_agregar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Btn_agregar.setBorderPainted(false);
        Btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_agregarActionPerformed(evt);
            }
        });

        Btn_modificar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Btn_modificar.setForeground(new java.awt.Color(0, 0, 0));
        Btn_modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/icono_modificar.png"))); // NOI18N
        Btn_modificar.setText("Modificar");
        Btn_modificar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Btn_modificar.setBorderPainted(false);

        Btn_eliminar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Btn_eliminar.setForeground(new java.awt.Color(0, 0, 0));
        Btn_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/icono_eliminar.png"))); // NOI18N
        Btn_eliminar.setText("Eliminar");
        Btn_eliminar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Btn_eliminar.setBorderPainted(false);
        Btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_eliminarActionPerformed(evt);
            }
        });

        Lbl_precio.setText("Precio:");

        Btn_volver.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Btn_volver.setText("Volver al menu");
        Btn_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_volverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 736, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Btn_volver)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Lbl_numdetalle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Txt_numdetalle, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Lbl_numfactura1)
                                .addGap(18, 18, 18)
                                .addComponent(Txt_numfactura, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(85, 85, 85)
                                .addComponent(Lbl_Cantidad)
                                .addGap(18, 18, 18)
                                .addComponent(Cmb_Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(Lbl_precio)
                                .addGap(18, 18, 18)
                                .addComponent(Txt_precio, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(jLabel1)
                                .addGap(64, 64, 64)
                                .addComponent(Btn_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Btn_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Btn_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 48, Short.MAX_VALUE)))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_agregar)
                    .addComponent(Btn_modificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Btn_eliminar)
                    .addComponent(Btn_volver)
                    .addComponent(jLabel1))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl_Cantidad)
                    .addComponent(Cmb_Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lbl_precio)
                    .addComponent(Txt_precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Txt_numfactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lbl_numfactura1)
                    .addComponent(Lbl_numdetalle)
                    .addComponent(Txt_numdetalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_eliminarActionPerformed
        // TODO add your handling code here:
        boolean elimina = false;
        int num_detalle =  Integer.parseInt(Txt_numdetalle.getText());
        
        C_Detallle de = new C_Detallle();

        try
        {
            elimina = de.Eliminar(num_detalle);
            if(elimina == true)
            {
                JOptionPane.showMessageDialog(null, "Se eliminó la información ", "Información", JOptionPane.INFORMATION_MESSAGE);
            }
            else
            {
                JOptionPane.showMessageDialog(null, "No se eliminó la información ", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        catch(SQLException ex)
        {

        }
        LimpiarTabla();
        LlenarTabla();
        LimpiarCampos();
    }//GEN-LAST:event_Btn_eliminarActionPerformed

    private void Btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_agregarActionPerformed
        // TODO add your handling code here:
        
        
        
        
    }//GEN-LAST:event_Btn_agregarActionPerformed

    private void Txt_numdetalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_numdetalleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_numdetalleActionPerformed

    private void Btn_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_volverActionPerformed
        // TODO add your handling code here:
        JF_Menu obj = new JF_Menu();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_Btn_volverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_Detalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_Detalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_Detalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_Detalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_Detalle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_agregar;
    private javax.swing.JButton Btn_eliminar;
    private javax.swing.JButton Btn_modificar;
    private javax.swing.JButton Btn_volver;
    private javax.swing.JComboBox<String> Cmb_Cantidad;
    private javax.swing.JLabel Lbl_Cantidad;
    private javax.swing.JLabel Lbl_numdetalle;
    private javax.swing.JLabel Lbl_numfactura1;
    private javax.swing.JLabel Lbl_precio;
    private javax.swing.JTable Tbl_Detalle;
    private javax.swing.JTextField Txt_numdetalle;
    private javax.swing.JTextField Txt_numfactura;
    private javax.swing.JTextField Txt_precio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
