/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Controllers.C_Categoria;
import Controllers.C_Detalle;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Paulo
 */
public class JF_Categoria extends javax.swing.JFrame {

    /**
     * Creates new form JF_Categoria
     */
    public JF_Categoria() 
    {
        initComponents();
        LimpiarTabla();
        LlenarTabla();
    }
    
    //metodo que limpia la tabla
    public void LimpiarTabla()
    {
        
        for(int i = 0; i < TBl_categoria.getRowCount(); i++)
        {
            DefaultTableModel m = (DefaultTableModel) TBl_categoria.getModel();
            m.removeRow(i);
            i -= 1;
        }  
    }
    
    //llenamos la tabla
    public void LlenarTabla()
    {
        Object[][] Temca = null;
        //llamo al metodo de la clase que realiza el llenado 
        C_Categoria categorias = new C_Categoria();
        Temca = categorias.cargarTabla();
        
        DefaultTableModel modelo3 = (DefaultTableModel) TBl_categoria.getModel();
        
        for(int i = 0; i < Temca.length; i++)
        {
            modelo3.addRow(Temca[i]);
        }
        TBl_categoria.setModel(modelo3);   
    }
    
    public void MostrarTabla()
    { 
        int id_categoria = 0;
        String c = "";
        
        DefaultTableModel m2 = (DefaultTableModel) TBl_categoria.getModel();
        String id = String.valueOf(m2.getValueAt(TBl_categoria.getSelectedRow(), 1));
        String nombre = String.valueOf(m2.getValueAt(TBl_categoria.getSelectedRow(), 2));
        String descripcion = String.valueOf(m2.getValueAt(TBl_categoria.getSelectedRow(), 3));
 
        id_categoria = Integer.parseInt(id);
        String idF = Integer.toString(id_categoria);
        
        C_Categoria obj = new C_Categoria();
        
        if(Cbm_categorias.getSelectedIndex() == 0)
        {
            c = "Hogar";
        }
        else if (Cbm_categorias.getSelectedIndex() == 1)
        {
            c = "Salud";
        }
        else if(Cbm_categorias.getSelectedIndex() == 2)
        {
            c = "Alimentacion";
        }
        else if(Cbm_categorias.getSelectedIndex() == 3)
        {
            c = "Trasnporte";
        }
        else if(Cbm_categorias.getSelectedIndex() == 4)
        {
            c = "Mantenimiento";
        }
        
        try
        {
            if(Txt_descripcion.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(null, "No se puede guardar ya que falta la información ", "Error", JOptionPane.ERROR_MESSAGE);
            }
            else
            {
                id_categoria = obj.Guardar(nombre, descripcion);
            }
        }
        catch(SQLException ex)
        {
            Logger.getLogger(JF_Categoria.class.getName()).log(Level.SEVERE, null, ex);
        }
        LimpiarTabla();
        LlenarTabla();
        LimpiarCampos(); 
    }
    
    public void LimpiarCampos()
    {
        Txt_descripcion.setText("");
        Cbm_categorias.setSelectedIndex(0);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Lbl_categoria = new javax.swing.JLabel();
        Txt_idcategoria = new javax.swing.JTextField();
        Lbl_nombre = new javax.swing.JLabel();
        Cbm_categorias = new javax.swing.JComboBox<>();
        Lbl_descripcion = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TBl_categoria = new javax.swing.JTable();
        Btn_Menu = new javax.swing.JButton();
        Btn_agregar = new javax.swing.JButton();
        Btn_modificar = new javax.swing.JButton();
        Btn_Eliminar = new javax.swing.JButton();
        Txt_descripcion = new javax.swing.JTextField();
        Lbl_eliminardetalle = new javax.swing.JLabel();
        Txt_eliminarcategoria = new javax.swing.JTextField();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel2.setText("Categoría");

        Lbl_categoria.setText("ID:");

        Txt_idcategoria.setEnabled(false);

        Lbl_nombre.setText("Nombre:");

        Cbm_categorias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hogar", "Salud", "Alimentación", "Transporte", "Mantenimiento" }));

        Lbl_descripcion.setText("Descripción:");

        TBl_categoria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID Categoría", "Nombre", "Descripción"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(TBl_categoria);
        if (TBl_categoria.getColumnModel().getColumnCount() > 0) {
            TBl_categoria.getColumnModel().getColumn(0).setResizable(false);
            TBl_categoria.getColumnModel().getColumn(1).setResizable(false);
            TBl_categoria.getColumnModel().getColumn(2).setResizable(false);
        }

        Btn_Menu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Btn_Menu.setText("Volver al menu");
        Btn_Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_MenuActionPerformed(evt);
            }
        });

        Btn_agregar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Btn_agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/icono_agregar.png"))); // NOI18N
        Btn_agregar.setText("Agregar");
        Btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_agregarActionPerformed(evt);
            }
        });

        Btn_modificar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Btn_modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/icono_modificar.png"))); // NOI18N
        Btn_modificar.setText("Modificar");
        Btn_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_modificarActionPerformed(evt);
            }
        });

        Btn_Eliminar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Btn_Eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/icono_eliminar.png"))); // NOI18N
        Btn_Eliminar.setText("Eliminar");
        Btn_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_EliminarActionPerformed(evt);
            }
        });

        Lbl_eliminardetalle.setText("ID Categoria a eliminar:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Lbl_eliminardetalle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Txt_eliminarcategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(Btn_Eliminar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Btn_Menu)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(Btn_agregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Btn_modificar)
                        .addGap(151, 151, 151))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Lbl_categoria)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Txt_idcategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Lbl_nombre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Cbm_categorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(Lbl_descripcion)
                                .addGap(18, 18, 18)
                                .addComponent(Txt_descripcion))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 664, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Btn_Menu)
                            .addComponent(jLabel2)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Btn_agregar)
                        .addComponent(Btn_modificar)))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl_categoria)
                    .addComponent(Txt_idcategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lbl_nombre)
                    .addComponent(Cbm_categorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lbl_descripcion)
                    .addComponent(Txt_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl_eliminardetalle)
                    .addComponent(Txt_eliminarcategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Eliminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_MenuActionPerformed
        // TODO add your handling code here:
        JF_Menu obj = new JF_Menu();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_Btn_MenuActionPerformed

    private void Btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_agregarActionPerformed
        // TODO add your handling code here:
        int categoria;
        String nombre = "", descripcion;
        
        descripcion = Txt_descripcion.getText().toString();
        C_Categoria cate = new C_Categoria();
        
        if(Cbm_categorias.getSelectedIndex() == 0)
        {
            nombre = "Hogar";
        }
        else if (Cbm_categorias.getSelectedIndex() == 1)
        {
            nombre = "Salud";
        }
        else if(Cbm_categorias.getSelectedIndex() == 2)
        {
            nombre = "Alimentacion";
        }
        else if(Cbm_categorias.getSelectedIndex() == 3)
        {
            nombre = "Transporte";
        }
        else if(Cbm_categorias.getSelectedIndex() == 4)
        {
            nombre = "Mantenimiento";
        }
        
        try
        {
            if(Txt_descripcion.getText().isEmpty() || Cbm_categorias.getSelectedIndex() == 0)
            {
                JOptionPane.showMessageDialog(null, "No se puede guardar ya que falta la información ", "Error", JOptionPane.ERROR_MESSAGE);
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Guardada la informacion", "Guardado", JOptionPane.INFORMATION_MESSAGE);
                categoria = cate.Guardar(nombre, descripcion);
            }
        }
        catch(SQLException ex)
        {
            Logger.getLogger(JF_Categoria.class.getName()).log(Level.SEVERE, null, ex);
        }
        LimpiarTabla();
        LlenarTabla();
        LimpiarCampos();
    }//GEN-LAST:event_Btn_agregarActionPerformed

    private void Btn_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_modificarActionPerformed
        // TODO add your handling code here:
        int cate;
        String nom = "", desc;
        
        cate = Integer.parseInt(Txt_idcategoria.getText().toString());
        desc = Txt_descripcion.getText().toString();
        
        C_Categoria ob = new C_Categoria();
        
        if(Cbm_categorias.getSelectedIndex() == 0)
        {
            nom = "Hogar";
        }
        else if (Cbm_categorias.getSelectedIndex() == 1)
        {
            nom = "Salud";
        }
        else if(Cbm_categorias.getSelectedIndex() == 2)
        {
            nom = "Alimentacion";
        }
        else if(Cbm_categorias.getSelectedIndex() == 3)
        {
            nom = "Transporte";
        }
        else if(Cbm_categorias.getSelectedIndex() == 4)
        {
            nom = "Mantenimiento";
        }
        
        if(Txt_descripcion.getText().isEmpty() || Cbm_categorias.getSelectedIndex() == 0)
        {
            JOptionPane.showMessageDialog(null, "No se puede modificar ya que falta la información ", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Modificada la informacion", "Guardado", JOptionPane.INFORMATION_MESSAGE);
            if(ob.Modificar(cate, nom, desc) == true)
            {
                JOptionPane.showMessageDialog(null, "Se modificó la información correctamente ", "Informativo", JOptionPane.INFORMATION_MESSAGE);
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Modificada la informacion", "Guardado", JOptionPane.INFORMATION_MESSAGE); 
            }
        }

        LimpiarTabla();
        LlenarTabla();
        LimpiarCampos();
  
    }//GEN-LAST:event_Btn_modificarActionPerformed

    private void Btn_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_EliminarActionPerformed
        // TODO add your handling code here:      
        boolean elimina = false;
        int id = Integer.parseInt(Txt_eliminarcategoria.getText());
        
        C_Categoria c = new C_Categoria();
         
        if(Txt_eliminarcategoria.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Digite ID Categoria para eliminar", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        int cate =  Integer.parseInt(Txt_eliminarcategoria.getText());


        try
        {
            elimina = c.Eliminar(cate);
            if(elimina == true)
            {
                JOptionPane.showMessageDialog(null, "Se eliminó la información ", "Información", JOptionPane.INFORMATION_MESSAGE);
            }
            else
            {
                JOptionPane.showMessageDialog(null, "No se eliminó la información ", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(null, "Error al eliminar: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        LimpiarTabla();
        LlenarTabla();
        LimpiarCampos();
   
    }//GEN-LAST:event_Btn_EliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_Categoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_Categoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_Categoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_Categoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_Categoria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Eliminar;
    private javax.swing.JButton Btn_Menu;
    private javax.swing.JButton Btn_agregar;
    private javax.swing.JButton Btn_modificar;
    private javax.swing.JComboBox<String> Cbm_categorias;
    private javax.swing.JLabel Lbl_categoria;
    private javax.swing.JLabel Lbl_descripcion;
    private javax.swing.JLabel Lbl_eliminardetalle;
    private javax.swing.JLabel Lbl_nombre;
    private javax.swing.JTable TBl_categoria;
    private javax.swing.JTextField Txt_descripcion;
    private javax.swing.JTextField Txt_eliminarcategoria;
    private javax.swing.JTextField Txt_idcategoria;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
