/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Controllers.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;

public class JF_Detalle extends javax.swing.JFrame {

    /**
     * Creates new form JF_Detalle
     */
    public JF_Detalle() 
    {
        initComponents();
        LimpiarTabla();
        LlenarTabla();   
    }
    
    //metodo que limpia la tabla
    public void LimpiarTabla()
    {
        
        for(int i = 0; i < Tbl_Detalle.getRowCount(); i++)
        {
            DefaultTableModel m = (DefaultTableModel) Tbl_Detalle.getModel();
            m.removeRow(i);
            i -= 1;
        }  
    }
    
    //llenamos la tabla
    public void LlenarTabla()
    {
        
        Object[][] TemDet = null;
        //llamo al metodo de la clase que realiza el llenado 
        C_Detalle det = new C_Detalle();
        TemDet = det.cargarTabla();
        
        DefaultTableModel modelo3 = (DefaultTableModel) Tbl_Detalle.getModel();
        
        for(int i = 0; i < TemDet.length; i++)
        {
            modelo3.addRow(TemDet[i]);
        }
        Tbl_Detalle.setModel(modelo3);   
    }
    
    //mostrar data 
    public void MostrarTabla()
    { 
        int num_detalle = 0, can = 0;
        
        DefaultTableModel m2 = (DefaultTableModel) Tbl_Detalle.getModel();
        String id = String.valueOf(m2.getValueAt(Tbl_Detalle.getSelectedRow(), 1));
        String factura = String.valueOf(m2.getValueAt(Tbl_Detalle.getSelectedRow(), 2));
        String producto = String.valueOf(m2.getValueAt(Tbl_Detalle.getSelectedRow(), 3));
        String cantidad = String.valueOf(m2.getValueAt(Tbl_Detalle.getSelectedRow(), 4));
        String precio = String.valueOf(m2.getValueAt(Tbl_Detalle.getSelectedRow(), 5));
        
        num_detalle = Integer.parseInt(id);
        String idC = Integer.toString(num_detalle);
        
        Txt_numdetalle.setText(idC);
        Txt_numfactura.setText(factura);
        Txt_producto.setText(producto);
        Txt_cantidad.setText(cantidad);
        Txt_precio.setText(precio);         
    }
    
    public void LimpiarCampos()
    {
        Txt_numdetalle.setText("");
        Txt_numfactura.setText("");
        Txt_producto.setText("");
        Txt_cantidad.setText("");
        Txt_precio.setText(""); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Lbl_numdetalle = new javax.swing.JLabel();
        Lbl_numfactura1 = new javax.swing.JLabel();
        Lbl_Cantidad = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tbl_Detalle = new javax.swing.JTable();
        Txt_numdetalle = new javax.swing.JTextField();
        Txt_numfactura = new javax.swing.JTextField();
        Btn_agregar = new javax.swing.JButton();
        Btn_modificar = new javax.swing.JButton();
        Btn_eliminar = new javax.swing.JButton();
        Lbl_precio = new javax.swing.JLabel();
        Txt_precio = new javax.swing.JTextField();
        Btn_volver = new javax.swing.JButton();
        Txt_cantidad = new javax.swing.JTextField();
        Lbl_producto = new javax.swing.JLabel();
        Txt_producto = new javax.swing.JTextField();
        Btn_refrescar = new javax.swing.JButton();
        Lbl_eliminardetalle = new javax.swing.JLabel();
        Txt_eliminardetalle = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel1.setText("Detalle");

        Lbl_numdetalle.setText("Detalle:");

        Lbl_numfactura1.setText("Factura:");

        Lbl_Cantidad.setText("Cantidad:");

        Tbl_Detalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Detalle", "ID Factura", "ID Producto", "Cantidad", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tbl_Detalle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tbl_DetalleMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tbl_Detalle);
        if (Tbl_Detalle.getColumnModel().getColumnCount() > 0) {
            Tbl_Detalle.getColumnModel().getColumn(0).setResizable(false);
            Tbl_Detalle.getColumnModel().getColumn(1).setResizable(false);
            Tbl_Detalle.getColumnModel().getColumn(2).setResizable(false);
            Tbl_Detalle.getColumnModel().getColumn(3).setResizable(false);
            Tbl_Detalle.getColumnModel().getColumn(4).setResizable(false);
        }

        Txt_numdetalle.setEnabled(false);
        Txt_numdetalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_numdetalleActionPerformed(evt);
            }
        });

        Btn_agregar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Btn_agregar.setForeground(new java.awt.Color(0, 0, 0));
        Btn_agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/icono_agregar.png"))); // NOI18N
        Btn_agregar.setText("Agregar");
        Btn_agregar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Btn_agregar.setBorderPainted(false);
        Btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_agregarActionPerformed(evt);
            }
        });

        Btn_modificar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Btn_modificar.setForeground(new java.awt.Color(0, 0, 0));
        Btn_modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/icono_modificar.png"))); // NOI18N
        Btn_modificar.setText("Modificar");
        Btn_modificar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Btn_modificar.setBorderPainted(false);
        Btn_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_modificarActionPerformed(evt);
            }
        });

        Btn_eliminar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Btn_eliminar.setForeground(new java.awt.Color(0, 0, 0));
        Btn_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/icono_eliminar.png"))); // NOI18N
        Btn_eliminar.setText("Eliminar");
        Btn_eliminar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Btn_eliminar.setBorderPainted(false);
        Btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_eliminarActionPerformed(evt);
            }
        });

        Lbl_precio.setText("Precio:");

        Btn_volver.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Btn_volver.setText("Volver al menu");
        Btn_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_volverActionPerformed(evt);
            }
        });

        Lbl_producto.setText("Producto:");

        Btn_refrescar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Btn_refrescar.setText("Refrescar");
        Btn_refrescar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_refrescarActionPerformed(evt);
            }
        });

        Lbl_eliminardetalle.setText("ID Detalle a eliminar:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Lbl_numdetalle)
                        .addGap(18, 18, 18)
                        .addComponent(Txt_numdetalle, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Lbl_numfactura1)
                        .addGap(18, 18, 18)
                        .addComponent(Txt_numfactura, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Lbl_producto)
                        .addGap(18, 18, 18)
                        .addComponent(Txt_producto, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(Lbl_Cantidad)
                        .addGap(18, 18, 18)
                        .addComponent(Txt_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Lbl_precio)
                        .addGap(18, 18, 18)
                        .addComponent(Txt_precio, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Btn_volver)
                        .addGap(44, 44, 44)
                        .addComponent(jLabel1)
                        .addGap(50, 50, 50)
                        .addComponent(Btn_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Btn_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Btn_refrescar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Lbl_eliminardetalle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Txt_eliminardetalle, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Btn_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_agregar)
                    .addComponent(Btn_modificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Btn_volver)
                    .addComponent(jLabel1)
                    .addComponent(Btn_refrescar))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl_Cantidad)
                    .addComponent(Lbl_precio)
                    .addComponent(Txt_precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Txt_numfactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lbl_numfactura1)
                    .addComponent(Lbl_numdetalle)
                    .addComponent(Txt_numdetalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Txt_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lbl_producto)
                    .addComponent(Txt_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl_eliminardetalle)
                    .addComponent(Txt_eliminardetalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_eliminar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 722, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_eliminarActionPerformed
        // TODO add your handling code here:
        boolean elimina = false;
        if(Txt_eliminardetalle.getText().isEmpty()) 
        {
            JOptionPane.showMessageDialog(null, "Digite ID detalle para eliminar", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int num_detalle =  Integer.parseInt(Txt_eliminardetalle.getText());

        C_Detalle de = new C_Detalle();

        try
        {
            elimina = de.Eliminar(num_detalle);
            if(elimina == true)
            {
                JOptionPane.showMessageDialog(null, "Se eliminó la información ", "Información", JOptionPane.INFORMATION_MESSAGE);
            }
            else
            {
                JOptionPane.showMessageDialog(null, "No se eliminó la información ", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(null, "Error al eliminar: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        LimpiarTabla();
        LlenarTabla();
        LimpiarCampos();
    }//GEN-LAST:event_Btn_eliminarActionPerformed

    private void Btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_agregarActionPerformed
        // TODO add your handling code here:
        int num_detalle, factura, producto, cantidad;
        float precio;
        int id;

        if (Txt_numfactura.getText().isEmpty() || Txt_producto.getText().isEmpty() || Txt_cantidad.getText().isEmpty() || Txt_precio.getText().isEmpty()) 
        {
            JOptionPane.showMessageDialog(null, "Por favor, completa la informacion", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            factura = Integer.parseInt(Txt_numfactura.getText());
            producto = Integer.parseInt(Txt_producto.getText());
            precio = Float.parseFloat(Txt_precio.getText());
            cantidad = Integer.parseInt(Txt_cantidad.getText().toString());

            C_Detalle deta = new C_Detalle();
            id = deta.Guardar(factura, producto, cantidad, precio);
        } 
        catch (NumberFormatException e) 
        {
            JOptionPane.showMessageDialog(null, "Ingrese valores numéricos válidos para el número de factura y el precio.", "Error", JOptionPane.ERROR_MESSAGE);
        } 
        catch (SQLException ex) 
        {
            JOptionPane.showMessageDialog(null, "Error de base de datos al agregar: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        LimpiarTabla();
        LlenarTabla();
        LimpiarCampos();
    }//GEN-LAST:event_Btn_agregarActionPerformed

    private void Txt_numdetalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_numdetalleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_numdetalleActionPerformed

    private void Btn_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_volverActionPerformed
        // TODO add your handling code here:
        JF_Menu obj = new JF_Menu();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_Btn_volverActionPerformed

    private void Btn_refrescarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_refrescarActionPerformed
        // TODO add your handling code here:
        LimpiarTabla();
        LlenarTabla();
    }//GEN-LAST:event_Btn_refrescarActionPerformed

    private void Tbl_DetalleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tbl_DetalleMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount() == 2)
            MostrarTabla();
            
    }//GEN-LAST:event_Tbl_DetalleMouseClicked

    private void Btn_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_modificarActionPerformed
        // TODO add your handling code here:
        int num_detalle, factura, producto, cantidad;
        float precio;
        int id;

        if (Txt_numfactura.getText().isEmpty() || Txt_producto.getText().isEmpty() || Txt_cantidad.getText().isEmpty() || Txt_precio.getText().isEmpty()) 
        {
            JOptionPane.showMessageDialog(null, "Por favor, completa la informacion", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            id = Integer.parseInt(Txt_numdetalle.getText().toString());
            factura = Integer.parseInt(Txt_numfactura.getText());
            producto = Integer.parseInt(Txt_producto.getText());
            precio = Float.parseFloat(Txt_precio.getText());
            cantidad = Integer.parseInt(Txt_cantidad.getText().toString());

            C_Detalle deta = new C_Detalle();
            id = deta.Guardar(factura, producto, cantidad, precio);
            
            if(deta.Modificar(id, factura, producto, cantidad, precio) == true)
            {
                  JOptionPane.showMessageDialog(null, "Se modificó la información correctamente ", "Informativo", JOptionPane.INFORMATION_MESSAGE);
            }
        } 
        catch (NumberFormatException e) 
        {
            JOptionPane.showMessageDialog(null, "Ingrese valores numéricos válidos para el número de factura y el precio.", "Error", JOptionPane.ERROR_MESSAGE);
        } 
        catch (SQLException ex) 
        {
            JOptionPane.showMessageDialog(null, "Error de actualizacion de base de datos al agregar: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        LimpiarTabla();
        LlenarTabla();
        LimpiarCampos();
        
    }//GEN-LAST:event_Btn_modificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_Detalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_Detalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_Detalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_Detalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_Detalle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_agregar;
    private javax.swing.JButton Btn_eliminar;
    private javax.swing.JButton Btn_modificar;
    private javax.swing.JButton Btn_refrescar;
    private javax.swing.JButton Btn_volver;
    private javax.swing.JLabel Lbl_Cantidad;
    private javax.swing.JLabel Lbl_eliminardetalle;
    private javax.swing.JLabel Lbl_numdetalle;
    private javax.swing.JLabel Lbl_numfactura1;
    private javax.swing.JLabel Lbl_precio;
    private javax.swing.JLabel Lbl_producto;
    private javax.swing.JTable Tbl_Detalle;
    private javax.swing.JTextField Txt_cantidad;
    private javax.swing.JTextField Txt_eliminardetalle;
    private javax.swing.JTextField Txt_numdetalle;
    private javax.swing.JTextField Txt_numfactura;
    private javax.swing.JTextField Txt_precio;
    private javax.swing.JTextField Txt_producto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
