/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Controllers.C_Cliente;
import javax.swing.table.DefaultTableModel;
import Controllers.C_Factura;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author Paulo
 */
public class JF_Factura extends javax.swing.JFrame {

    /**
     * Creates new form JF_Factura
     */
    public JF_Factura() 
    {
        initComponents();
        LimpiarTabla();
        LlenarTabla();
    }
    
    //metodo que limpia la tabla
    public void LimpiarTabla()
    {
        
        for(int i = 0; i < Tbl_factura.getRowCount(); i++)
        {
            DefaultTableModel m = (DefaultTableModel) Tbl_factura.getModel();
            m.removeRow(i);
            i -= 1;
        }  
    }
    
    //llenamos la tabla
    public void LlenarTabla()
    {
        Object[][] Temfa = null;
        //llamo al metodo de la clase que realiza el llenado 
        C_Factura facturas = new C_Factura();
        Temfa = facturas.cargarTabla();
        
        DefaultTableModel modelo3 = (DefaultTableModel) Tbl_factura.getModel();
        
        for(int i = 0; i < Temfa.length; i++)
        {
            modelo3.addRow(Temfa[i]);
        }
        Tbl_factura.setModel(modelo3);   
    }
    
    //mostrar data 
    public void MostrarTabla()
    { 
        int num_factura = 0;
        
        DefaultTableModel m2 = (DefaultTableModel) Tbl_factura.getModel();
        String id = String.valueOf(m2.getValueAt(Tbl_factura.getSelectedRow(), 1));
        String num_pago = String.valueOf(m2.getValueAt(Tbl_factura.getSelectedRow(), 2));
        String fecha = String.valueOf(m2.getValueAt(Tbl_factura.getSelectedRow(), 3));
        String nombre = String.valueOf(m2.getValueAt(Tbl_factura.getSelectedRow(), 4));

  
        num_factura = Integer.parseInt(id);
        String idF = Integer.toString(num_factura);
        
        Txt_idfactura.setText(idF);
        Txt_fecha.setText(fecha);
        Txt_numpago.setText(num_pago); 
        Txt_idcliente.setText(nombre);  
    }
    
    public void LimpiarCampos()
    {
        Txt_idfactura.setText("");
        Txt_fecha.setText("");
        Txt_numpago.setText(""); 
        Txt_idcliente.setText(""); 
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Lbl_Factura = new javax.swing.JLabel();
        Btn_Menu = new javax.swing.JButton();
        Btn_Guardar = new javax.swing.JButton();
        Btn_Modificar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        Btn_buscar = new javax.swing.JButton();
        Lbl_idfactura = new javax.swing.JLabel();
        Txt_idfactura = new javax.swing.JTextField();
        Lbl_idcliente = new javax.swing.JLabel();
        Txt_idcliente = new javax.swing.JTextField();
        Lbl_fecha = new javax.swing.JLabel();
        Txt_fecha = new javax.swing.JTextField();
        Lbl_numpago = new javax.swing.JLabel();
        Txt_numpago = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tbl_factura = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Lbl_Factura.setFont(new java.awt.Font("Segoe UI", 3, 48)); // NOI18N
        Lbl_Factura.setText("Factura");

        Btn_Menu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Btn_Menu.setText("Volver al menu");
        Btn_Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_MenuActionPerformed(evt);
            }
        });

        Btn_Guardar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Btn_Guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/icono_agregar.png"))); // NOI18N
        Btn_Guardar.setText("Agregar");
        Btn_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_GuardarActionPerformed(evt);
            }
        });

        Btn_Modificar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Btn_Modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/icono_modificar.png"))); // NOI18N
        Btn_Modificar.setText("Modificar");

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/icono_eliminar.png"))); // NOI18N
        jButton1.setText("Eliminar");

        Btn_buscar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Btn_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/icono_buscar.png"))); // NOI18N
        Btn_buscar.setText("Buscar");

        Lbl_idfactura.setText("Factura:");

        Txt_idfactura.setEnabled(false);

        Lbl_idcliente.setText("ID Cliente:");

        Lbl_fecha.setText("Fecha:");

        Txt_fecha.setText("AAAA-MM-DD");

        Lbl_numpago.setText("Pago:");

        Tbl_factura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Fecha", "Cliente", "Pago", "Factura"
            }
        ));
        jScrollPane1.setViewportView(Tbl_factura);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 39, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Btn_Menu)
                                .addGap(79, 79, 79)
                                .addComponent(Lbl_Factura))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Lbl_fecha)
                                .addGap(18, 18, 18)
                                .addComponent(Txt_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(Lbl_numpago)
                                .addGap(18, 18, 18)
                                .addComponent(Txt_numpago, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Lbl_idfactura)
                                .addGap(18, 18, 18)
                                .addComponent(Txt_idfactura, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Lbl_idcliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Txt_idcliente)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Btn_Modificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Btn_Guardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Btn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(42, 42, 42))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Btn_Menu)
                            .addComponent(Lbl_Factura))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Lbl_fecha)
                            .addComponent(Txt_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lbl_numpago)
                            .addComponent(Txt_numpago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lbl_idfactura)
                            .addComponent(Txt_idfactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Txt_idcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lbl_idcliente))
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(Btn_Guardar)
                        .addGap(15, 15, 15)
                        .addComponent(Btn_Modificar)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Btn_buscar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_MenuActionPerformed
        // TODO add your handling code here:
        JF_Menu obj = new JF_Menu();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_Btn_MenuActionPerformed

    private void Btn_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_GuardarActionPerformed
        // TODO add your handling code here:
        int num_factura, factura;
        
        String fecha, cliente, pago;
        
        fecha = Txt_fecha.getText().toString();
        pago = Txt_numpago.getText().toString();
        factura = Integer.parseInt(Txt_idfactura.getText().toString());
        int p = Integer.parseInt(pago);
        cliente = Txt_idcliente.getText().toString();
        
        C_Factura facturas = new C_Factura();
        
        try
        {
            if(Txt_fecha.getText().toString().isEmpty() || Txt_numpago.getText().toString().isEmpty() 
                    || Txt_idfactura.getText().toString().isEmpty() || Txt_idcliente.getText().toString().isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Falta ingresar informacion", "Error", JOptionPane.ERROR_MESSAGE);
            }
            else 
            {
                num_factura = facturas.Guardar(factura, p, fecha, cliente);
            }
        }
        catch(SQLException ex)
        {
            Logger.getLogger(JF_Cliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        LimpiarTabla();
        LlenarTabla();
        LimpiarCampos();
    }//GEN-LAST:event_Btn_GuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_Factura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Guardar;
    private javax.swing.JButton Btn_Menu;
    private javax.swing.JButton Btn_Modificar;
    private javax.swing.JButton Btn_buscar;
    private javax.swing.JLabel Lbl_Factura;
    private javax.swing.JLabel Lbl_fecha;
    private javax.swing.JLabel Lbl_idcliente;
    private javax.swing.JLabel Lbl_idfactura;
    private javax.swing.JLabel Lbl_numpago;
    private javax.swing.JTable Tbl_factura;
    private javax.swing.JTextField Txt_fecha;
    private javax.swing.JTextField Txt_idcliente;
    private javax.swing.JTextField Txt_idfactura;
    private javax.swing.JTextField Txt_numpago;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
