/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Controllers.C_ModoPago;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class JF_ModoPago extends javax.swing.JFrame 
{

    /**
     * Creates new form JF_ModoPago
     */
    public JF_ModoPago() 
    {
        initComponents();
        LimpiarTabla();
        LlenarTabla();
    }
    
    public void LimpiarTabla()
    {
        
        for(int i = 0; i < Tbl_ModoPago.getRowCount(); i++)
        {
            DefaultTableModel m = (DefaultTableModel) Tbl_ModoPago.getModel();
            m.removeRow(i);
            i -= 1;
        }  
    }
    
    public void LlenarTabla()
    {
        
        Object[][] TemCli = null;
        //llamo al metodo de la clase que realiza el llenado 
        C_ModoPago pago = new C_ModoPago();
        TemCli = pago.cargarTabla();
        
        DefaultTableModel modelo3 = (DefaultTableModel) Tbl_ModoPago.getModel();
        
        for(int i = 0; i < TemCli.length; i++)
        {
            modelo3.addRow(TemCli[i]);
        }
        Tbl_ModoPago.setModel(modelo3);   
    }
    
    public void MostrarTabla()
    { 
        int num_pago = 0;
        
        DefaultTableModel m2 = (DefaultTableModel) Tbl_ModoPago.getModel();
        String id = String.valueOf(m2.getValueAt(Tbl_ModoPago.getSelectedRow(), 1));
        String nombre = String.valueOf(m2.getValueAt(Tbl_ModoPago.getSelectedRow(), 2));
        String detalles = String.valueOf(m2.getValueAt(Tbl_ModoPago.getSelectedRow(), 3));
        
        num_pago = Integer.parseInt(id);
        String idC = Integer.toString(num_pago);
        
        Txt_numpago.setText(id);
        Txt_nompago.setText(nombre);
        Txt_detalles.setText(detalles);
    }    
    
    public void LimpiarCampos()
    {
        Txt_numpago.setText("");
        Txt_nompago.setText("");
        Txt_detalles.setText(""); 
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Lbl_numpago = new javax.swing.JLabel();
        Txt_numpago = new javax.swing.JTextField();
        Lbl_nompago = new javax.swing.JLabel();
        Txt_nompago = new javax.swing.JTextField();
        Lbl_detalles = new javax.swing.JLabel();
        Txt_detalles = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tbl_ModoPago = new javax.swing.JTable();
        Btn_regresar = new javax.swing.JButton();
        Btn_agregar = new javax.swing.JButton();
        Btn_modificar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel1.setText("Modo Pago");

        Lbl_numpago.setText("Numero de pago:");

        Txt_numpago.setEnabled(false);

        Lbl_nompago.setText("Nombre:");

        Lbl_detalles.setText("Detalles:");

        Tbl_ModoPago.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pago", "Nombre", "Detalles"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Tbl_ModoPago);
        if (Tbl_ModoPago.getColumnModel().getColumnCount() > 0) {
            Tbl_ModoPago.getColumnModel().getColumn(0).setResizable(false);
            Tbl_ModoPago.getColumnModel().getColumn(1).setResizable(false);
            Tbl_ModoPago.getColumnModel().getColumn(2).setResizable(false);
        }

        Btn_regresar.setText("Volver al menu");
        Btn_regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_regresarActionPerformed(evt);
            }
        });

        Btn_agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/icono_agregar.png"))); // NOI18N
        Btn_agregar.setText("Agregar");
        Btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_agregarActionPerformed(evt);
            }
        });

        Btn_modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/icono_modificar.png"))); // NOI18N
        Btn_modificar.setText("Modificar");
        Btn_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_modificarActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/icono_eliminar.png"))); // NOI18N
        jButton1.setText("Eliminar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Lbl_numpago)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Txt_numpago, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(Lbl_nompago)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Txt_nompago, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Lbl_detalles)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Txt_detalles, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(jLabel1)
                                .addGap(65, 65, 65)
                                .addComponent(Btn_agregar)
                                .addGap(18, 18, 18)
                                .addComponent(Btn_modificar)
                                .addGap(27, 27, 27)
                                .addComponent(jButton1))))
                    .addComponent(Btn_regresar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Btn_regresar)
                    .addComponent(Btn_agregar)
                    .addComponent(Btn_modificar)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl_numpago)
                    .addComponent(Txt_numpago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lbl_nompago)
                    .addComponent(Txt_nompago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lbl_detalles)
                    .addComponent(Txt_detalles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_regresarActionPerformed
        // TODO add your handling code here:
        JF_Menu obj = new JF_Menu();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_Btn_regresarActionPerformed

    private void Btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_agregarActionPerformed
        // TODO add your handling code here:
        int num_pago;
        String nombre, detalles;
        
        nombre = Txt_nompago.getText().toString();
        detalles = Txt_detalles.getText().toString();
        
        C_ModoPago nuevo = new C_ModoPago();
        
        try
        {
            if(Txt_nompago.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Falta ingresar el nombre del cliente", "Error", JOptionPane.ERROR_MESSAGE);
            }
            else if(Txt_detalles.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Falta ingresar detalles", "Error", JOptionPane.ERROR_MESSAGE);
            }
            num_pago = nuevo.Guardar(nombre, detalles);
        }
        catch(SQLException ex)
        {
            Logger.getLogger(JF_Cliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        LimpiarTabla();
        LlenarTabla();
        LimpiarCampos();
    }//GEN-LAST:event_Btn_agregarActionPerformed

    private void Btn_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_modificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_modificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_ModoPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_ModoPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_ModoPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_ModoPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_ModoPago().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_agregar;
    private javax.swing.JButton Btn_modificar;
    private javax.swing.JButton Btn_regresar;
    private javax.swing.JLabel Lbl_detalles;
    private javax.swing.JLabel Lbl_nompago;
    private javax.swing.JLabel Lbl_numpago;
    private javax.swing.JTable Tbl_ModoPago;
    private javax.swing.JTextField Txt_detalles;
    private javax.swing.JTextField Txt_nompago;
    private javax.swing.JTextField Txt_numpago;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
